name: Tests

permissions:
  contents: read
  statuses: write
  id-token: write

on:
  push:
    branches: ['**']  # Run on all branches
  pull_request:
    branches: ['**']  # Also run on PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Debug - List files
        run: ls -la
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Remove cache for now to avoid lock file issues
          # cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install coverage dependencies (optional)
        run: npm install @vitest/coverage-v8 --no-save
        continue-on-error: true  # Don't fail if coverage install fails
        
      - name: Run type check
        run: npx tsc --noEmit
        
      - name: Run tests
        run: npm test -- --run --reporter=verbose
        
      - name: Run test coverage
        run: npm run test:coverage -- --run
        continue-on-error: true  # Don't fail if coverage isn't configured
        
      - name: Build project
        run: npm run build
        env:
          VITE_RECAPTCHA_API_KEY: ${{ secrets.VITE_RECAPTCHA_API_KEY }}
        
      - name: Upload coverage reports
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
